<?php
/*-------------------------------------------------------+
| WebClearFusion Content Management System
| Copyright (C) 2010 - 2012 lovepsone
+--------------------------------------------------------+
| Filename: include_player_data.php
| Author: lovepsone
+--------------------------------------------------------+
| Removal of this copyright header is strictly prohibited 
| without written permission from the original author(s).
+--------------------------------------------------------*/

	// Characters extra_flag
	define('PLAYER_EXTRA_GM_ON',             0x0001);
	define('PLAYER_EXTRA_GM_ACCEPT_TICKETS', 0x0002);
	define('PLAYER_EXTRA_ACCEPT_WHISPERS',   0x0004);
	define('PLAYER_EXTRA_TAXICHEAT',         0x0008);
	define('PLAYER_EXTRA_GM_INVISIBLE',      0x0010);
	define('PLAYER_EXTRA_GM_CHAT',           0x0020); // Show GM badge in chat messages
	define('PLAYER_EXTRA_PVP_DEATH',         0x0100); // store PvP death status until corpse creating.

$qplevel = array('1'=>'1','2'=>'2','3'=>'3','4'=>'4','5'=>'5','6'=>'6','7'=>'7','8'=>'8','9'=>'9','10'=>'10','11'=>'11','12'=>'12','13'=>'13','14'=>'14','15'=>'15','16'=>'16','17'=>'17','18'=>'18','19'=>'19','20'=>'20','21'=>'21','22'=>'22','23'=>'23','24'=>'24','25'=>'25','26'=>'26','27'=>'27','28'=>'28','29'=>'29','30'=>'30',
 '31'=>'31','32'=>'32','33'=>'33','34'=>'34','35'=>'35','36'=>'36','37'=>'37','38'=>'38','39'=>'39','40'=>'40','41'=>'41','42'=>'42','43'=>'43','44'=>'44','45'=>'45','46'=>'46','47'=>'47','48'=>'48','49'=>'49','50'=>'50','51'=>'51','52'=>'52','53'=>'53','54'=>'54','55'=>'55','56'=>'56','57'=>'57','58'=>'58','59'=>'59','60'=>'60',
 '61'=>'61','62'=>'62','63'=>'63','64'=>'64','65'=>'65','66'=>'66','67'=>'67','68'=>'68','69'=>'69','70'=>'70','71'=>'71','72'=>'72','73'=>'73','74'=>'74','75'=>'75','76'=>'76','77'=>'77','78'=>'78','79'=>'79','80'=>'80');

	// Классы
	define('CLASS_WARRIOR',1);
	define('CLASS_PALADIN',2);
	define('CLASS_HUNTER',3);
	define('CLASS_ROGUE',4);
	define('CLASS_PRIEST',5);
	define('CLASS_DEATH_KNIGHT',6);
	define('CLASS_SHAMAN',7);
	define('CLASS_MAGE',8);
	define('CLASS_WARLOCK',9);
	define('CLASS_DRUID',11);
	// Тип энергии
	define('POWER_MANA', 0);
	define('POWER_RAGE', 1);
	define('POWER_FOCUS', 2);
	define('POWER_ENERGY', 3);
	define('POWER_HAPPINESS', 4);
	define('POWER_RUNE', 5);
	define('POWER_RUNIC_POWER', 6);
	// Тип стата
	define('STAT_STRENGTH', 0);
	define('STAT_AGILITY', 1);
	define('STAT_STAMINA', 2);
	define('STAT_INTELLECT', 3);
	define('STAT_SPIRIT', 4);
	// Тип школы/резиста
	define('SCHOOL_ARMOR', 0);
	define('SCHOOL_HOLY', 1);
	define('SCHOOL_FIRE', 2);
	define('SCHOOL_NATURE', 3);
	define('SCHOOL_FROST', 4);
	define('SCHOOL_SHADOW', 5);
	define('SCHOOL_ARCANE', 6);
	// Различные константы
	define('ATTACK_POWER_MAGIC_NUMBER',14);
	define('BLOCK_PER_STRENGTH', 0.5);
	define('HEALTH_PER_STAMINA', 10);
	define('ARMOR_PER_AGILITY', 2);
	define('MANA_PER_INTELLECT', 15);
	define('MANA_REGEN_PER_SPIRIT', 0.2);
	define('DODGE_PARRY_BLOCK_PERCENT_PER_DEFENSE', 0.04);
	define('RESILIENCE_CRIT_CHANCE_TO_DAMAGE_REDUCTION_MULTIPLIER', 2.2);;

	// Rating
	define('CR_WEAPON_SKILL',1);
	define('CR_DEFENSE_SKILL',2);
	define('CR_DODGE',3);
	define('CR_PARRY',4);
	define('CR_BLOCK',5);
	define('CR_HIT_MELEE',6);
	define('CR_HIT_RANGED',7);
	define('CR_HIT_SPELL',8);
	define('CR_CRIT_MELEE',9);
	define('CR_CRIT_RANGED',10);
	define('CR_CRIT_SPELL',11);
	define('CR_HIT_TAKEN_MELEE',12);
	define('CR_HIT_TAKEN_RANGED',13);
	define('CR_HIT_TAKEN_SPELL',14);
	define('CR_CRIT_TAKEN_MELEE',15);
	define('CR_CRIT_TAKEN_RANGED',16);
	define('CR_CRIT_TAKEN_SPELL',17);
	define('CR_HASTE_MELEE',18);
	define('CR_HASTE_RANGED',19);
	define('CR_HASTE_SPELL',20);
	define('CR_WEAPON_SKILL_MAINHAND',21);
	define('CR_WEAPON_SKILL_OFFHAND',22);
	define('CR_WEAPON_SKILL_RANGED',23);
	define('CR_EXPERTISE',24);
	define('CR_ARMOR_PENETRATION', 25);

	//Skills
	define('SKILL_SWORDS',43);
	define('SKILL_AXES',44);
	define('SKILL_BOWS',45);
	define('SKILL_GUNS',46);
	define('SKILL_MACES',54);
	define('SKILL_TWO_HANDED_SWORDS',55);
	define('SKILL_DEFENCE',95);
	define('SKILL_DUAL_WIELD',118);
	define('SKILL_STAVES',136);
	define('SKILL_TWO_HANDED_MACES',160);
	define('SKILL_UNARMED',162);
	define('SKILL_TWO_HANDED_AXE',172);
	define('SKILL_DAGGERS',173);
	define('SKILL_THROWN',176);
	define('SKILL_CROSSBOWS',226);
	define('SKILL_WANDS',228);
	define('SKILL_POLEARMS',229);
	define('SKILL_FIST_WEAPONS',473);

	define('OBJECT_FIELD_GUID', 0x0000);	// Size: 2, Type: LONG, Flags: PUBLIC
	define('OBJECT_FIELD_TYPE', 0x0002);	// Size: 1, Type: INT, Flags: PUBLIC
	define('OBJECT_FIELD_ENTRY', 0x0003);	// Size: 1, Type: INT, Flags: PUBLIC
	define('OBJECT_FIELD_SCALE_X', 0x0004);	// Size: 1, Type: FLOAT, Flags: PUBLIC
	define('OBJECT_FIELD_PADDING', 0x0005);	// Size: 1, Type: INT, Flags: NONE
	define('OBJECT_END', 0x0006);	//

	define('UNIT_FIELD_CHARM', OBJECT_END + 0x0000); // Size: 2, Type: LONG, Flags: PUBLIC
	define('UNIT_FIELD_SUMMON', OBJECT_END + 0x0002); // Size: 2, Type: LONG, Flags: PUBLIC
	define('UNIT_FIELD_CRITTER', OBJECT_END + 0x0004); // Size: 2, Type: LONG, Flags: PRIVATE
	define('UNIT_FIELD_CHARMEDBY', OBJECT_END + 0x0006); // Size: 2, Type: LONG, Flags: PUBLIC
	define('UNIT_FIELD_SUMMONEDBY', OBJECT_END + 0x0008); // Size: 2, Type: LONG, Flags: PUBLIC
	define('UNIT_FIELD_CREATEDBY', OBJECT_END + 0x000A); // Size: 2, Type: LONG, Flags: PUBLIC
	define('UNIT_FIELD_TARGET', OBJECT_END + 0x000C); // Size: 2, Type: LONG, Flags: PUBLIC
	define('UNIT_FIELD_CHANNEL_OBJECT', OBJECT_END + 0x000E); // Size: 2, Type: LONG, Flags: PUBLIC
	define('UNIT_FIELD_BYTES_0', OBJECT_END + 0x0010); // Size: 1, Type: BYTES, Flags: PUBLIC
	define('UNIT_FIELD_HEALTH', OBJECT_END + 0x0011); // Size: 1, Type: INT, Flags: PUBLIC
	define('UNIT_FIELD_POWER1', OBJECT_END + 0x0012); // Size: 1, Type: INT, Flags: PUBLIC
	define('UNIT_FIELD_POWER2', OBJECT_END + 0x0013); // Size: 1, Type: INT, Flags: PUBLIC
	define('UNIT_FIELD_POWER3', OBJECT_END + 0x0014); // Size: 1, Type: INT, Flags: PUBLIC
	define('UNIT_FIELD_POWER4', OBJECT_END + 0x0015); // Size: 1, Type: INT, Flags: PUBLIC
	define('UNIT_FIELD_POWER5', OBJECT_END + 0x0016); // Size: 1, Type: INT, Flags: PUBLIC
	define('UNIT_FIELD_POWER6', OBJECT_END + 0x0017); // Size: 1, Type: INT, Flags: PUBLIC
	define('UNIT_FIELD_POWER7', OBJECT_END + 0x0018); // Size: 1, Type: INT, Flags: PUBLIC
	define('UNIT_FIELD_MAXHEALTH', OBJECT_END + 0x0019); // Size: 1, Type: INT, Flags: PUBLIC
	define('UNIT_FIELD_MAXPOWER1', OBJECT_END + 0x001A); // Size: 1, Type: INT, Flags: PUBLIC
	define('UNIT_FIELD_MAXPOWER2', OBJECT_END + 0x001B); // Size: 1, Type: INT, Flags: PUBLIC
	define('UNIT_FIELD_MAXPOWER3', OBJECT_END + 0x001C); // Size: 1, Type: INT, Flags: PUBLIC
	define('UNIT_FIELD_MAXPOWER4', OBJECT_END + 0x001D); // Size: 1, Type: INT, Flags: PUBLIC
	define('UNIT_FIELD_MAXPOWER5', OBJECT_END + 0x001E); // Size: 1, Type: INT, Flags: PUBLIC
	define('UNIT_FIELD_MAXPOWER6', OBJECT_END + 0x001F); // Size: 1, Type: INT, Flags: PUBLIC
	define('UNIT_FIELD_MAXPOWER7', OBJECT_END + 0x0020); // Size: 1, Type: INT, Flags: PUBLIC
	define('UNIT_FIELD_POWER_REGEN_FLAT_MODIFIER', OBJECT_END + 0x0021); // Size: 7, Type: FLOAT, Flags: PRIVATE, OWNER
	define('UNIT_FIELD_POWER_REGEN_INTERRUPTED_FLAT_MODIFIER', OBJECT_END + 0x0028); // Size: 7, Type: FLOAT, Flags: PRIVATE, OWNER
	define('UNIT_FIELD_LEVEL', OBJECT_END + 0x002F); // Size: 1, Type: INT, Flags: PUBLIC
	define('UNIT_FIELD_FACTIONTEMPLATE', OBJECT_END + 0x0030); // Size: 1, Type: INT, Flags: PUBLIC
	define('UNIT_VIRTUAL_ITEM_SLOT_ID', OBJECT_END + 0x0031); // Size: 3, Type: INT, Flags: PUBLIC
	define('UNIT_FIELD_FLAGS', OBJECT_END + 0x0034); // Size: 1, Type: INT, Flags: PUBLIC
	define('UNIT_FIELD_FLAGS_2', OBJECT_END + 0x0035); // Size: 1, Type: INT, Flags: PUBLIC
	define('UNIT_FIELD_AURASTATE', OBJECT_END + 0x0036); // Size: 1, Type: INT, Flags: PUBLIC
	define('UNIT_FIELD_BASEATTACKTIME', OBJECT_END + 0x0037); // Size: 2, Type: INT, Flags: PUBLIC
	define('UNIT_FIELD_RANGEDATTACKTIME', OBJECT_END + 0x0039); // Size: 1, Type: INT, Flags: PRIVATE
	define('UNIT_FIELD_BOUNDINGRADIUS', OBJECT_END + 0x003A); // Size: 1, Type: FLOAT, Flags: PUBLIC
	define('UNIT_FIELD_COMBATREACH', OBJECT_END + 0x003B); // Size: 1, Type: FLOAT, Flags: PUBLIC
	define('UNIT_FIELD_DISPLAYID', OBJECT_END + 0x003C); // Size: 1, Type: INT, Flags: PUBLIC
	define('UNIT_FIELD_NATIVEDISPLAYID', OBJECT_END + 0x003D); // Size: 1, Type: INT, Flags: PUBLIC
	define('UNIT_FIELD_MOUNTDISPLAYID', OBJECT_END + 0x003E); // Size: 1, Type: INT, Flags: PUBLIC
	define('UNIT_FIELD_MINDAMAGE', OBJECT_END + 0x003F); // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER, PARTY_LEADER
	define('UNIT_FIELD_MAXDAMAGE', OBJECT_END + 0x0040); // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER, PARTY_LEADER
	define('UNIT_FIELD_MINOFFHANDDAMAGE', OBJECT_END + 0x0041); // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER, PARTY_LEADER
	define('UNIT_FIELD_MAXOFFHANDDAMAGE', OBJECT_END + 0x0042); // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER, PARTY_LEADER
	define('UNIT_FIELD_BYTES_1', OBJECT_END + 0x0043); // Size: 1, Type: BYTES, Flags: PUBLIC
	define('UNIT_FIELD_PETNUMBER', OBJECT_END + 0x0044); // Size: 1, Type: INT, Flags: PUBLIC
	define('UNIT_FIELD_PET_NAME_TIMESTAMP', OBJECT_END + 0x0045); // Size: 1, Type: INT, Flags: PUBLIC
	define('UNIT_FIELD_PETEXPERIENCE', OBJECT_END + 0x0046); // Size: 1, Type: INT, Flags: OWNER
	define('UNIT_FIELD_PETNEXTLEVELEXP', OBJECT_END + 0x0047); // Size: 1, Type: INT, Flags: OWNER
	define('UNIT_DYNAMIC_FLAGS', OBJECT_END + 0x0048); // Size: 1, Type: INT, Flags: DYNAMIC
	define('UNIT_CHANNEL_SPELL', OBJECT_END + 0x0049); // Size: 1, Type: INT, Flags: PUBLIC
	define('UNIT_MOD_CAST_SPEED', OBJECT_END + 0x004A); // Size: 1, Type: FLOAT, Flags: PUBLIC
	define('UNIT_CREATED_BY_SPELL', OBJECT_END + 0x004B); // Size: 1, Type: INT, Flags: PUBLIC
	define('UNIT_NPC_FLAGS', OBJECT_END + 0x004C); // Size: 1, Type: INT, Flags: DYNAMIC
	define('UNIT_NPC_EMOTESTATE', OBJECT_END + 0x004D); // Size: 1, Type: INT, Flags: PUBLIC
	define('UNIT_FIELD_STAT0', OBJECT_END + 0x004E); // Size: 1, Type: INT, Flags: PRIVATE, OWNER
	define('UNIT_FIELD_STAT1', OBJECT_END + 0x004F); // Size: 1, Type: INT, Flags: PRIVATE, OWNER
	define('UNIT_FIELD_STAT2', OBJECT_END + 0x0050); // Size: 1, Type: INT, Flags: PRIVATE, OWNER
	define('UNIT_FIELD_STAT3', OBJECT_END + 0x0051); // Size: 1, Type: INT, Flags: PRIVATE, OWNER
	define('UNIT_FIELD_STAT4', OBJECT_END + 0x0052); // Size: 1, Type: INT, Flags: PRIVATE, OWNER
	define('UNIT_FIELD_POSSTAT0', OBJECT_END + 0x0053); // Size: 1, Type: INT, Flags: PRIVATE, OWNER
	define('UNIT_FIELD_POSSTAT1', OBJECT_END + 0x0054); // Size: 1, Type: INT, Flags: PRIVATE, OWNER
	define('UNIT_FIELD_POSSTAT2', OBJECT_END + 0x0055); // Size: 1, Type: INT, Flags: PRIVATE, OWNER
	define('UNIT_FIELD_POSSTAT3', OBJECT_END + 0x0056); // Size: 1, Type: INT, Flags: PRIVATE, OWNER
	define('UNIT_FIELD_POSSTAT4', OBJECT_END + 0x0057); // Size: 1, Type: INT, Flags: PRIVATE, OWNER
	define('UNIT_FIELD_NEGSTAT0', OBJECT_END + 0x0058); // Size: 1, Type: INT, Flags: PRIVATE, OWNER
	define('UNIT_FIELD_NEGSTAT1', OBJECT_END + 0x0059); // Size: 1, Type: INT, Flags: PRIVATE, OWNER
	define('UNIT_FIELD_NEGSTAT2', OBJECT_END + 0x005A); // Size: 1, Type: INT, Flags: PRIVATE, OWNER
	define('UNIT_FIELD_NEGSTAT3', OBJECT_END + 0x005B); // Size: 1, Type: INT, Flags: PRIVATE, OWNER
	define('UNIT_FIELD_NEGSTAT4', OBJECT_END + 0x005C); // Size: 1, Type: INT, Flags: PRIVATE, OWNER
	define('UNIT_FIELD_RESISTANCES', OBJECT_END + 0x005D); // Size: 7, Type: INT, Flags: PRIVATE, OWNER, PARTY_LEADER
	define('UNIT_FIELD_RESISTANCEBUFFMODSPOSITIVE', OBJECT_END + 0x0064); // Size: 7, Type: INT, Flags: PRIVATE, OWNER
	define('UNIT_FIELD_RESISTANCEBUFFMODSNEGATIVE', OBJECT_END + 0x006B); // Size: 7, Type: INT, Flags: PRIVATE, OWNER
	define('UNIT_FIELD_BASE_MANA', OBJECT_END + 0x0072); // Size: 1, Type: INT, Flags: PUBLIC
	define('UNIT_FIELD_BASE_HEALTH', OBJECT_END + 0x0073); // Size: 1, Type: INT, Flags: PRIVATE, OWNER
	define('UNIT_FIELD_BYTES_2', OBJECT_END + 0x0074); // Size: 1, Type: BYTES, Flags: PUBLIC
	define('UNIT_FIELD_ATTACK_POWER', OBJECT_END + 0x0075); // Size: 1, Type: INT, Flags: PRIVATE, OWNER
	define('UNIT_FIELD_ATTACK_POWER_MODS', OBJECT_END + 0x0076); // Size: 1, Type: TWO_SHORT, Flags: PRIVATE, OWNER
	define('UNIT_FIELD_ATTACK_POWER_MULTIPLIER', OBJECT_END + 0x0077); // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER
	define('UNIT_FIELD_RANGED_ATTACK_POWER', OBJECT_END + 0x0078); // Size: 1, Type: INT, Flags: PRIVATE, OWNER
	define('UNIT_FIELD_RANGED_ATTACK_POWER_MODS', OBJECT_END + 0x0079); // Size: 1, Type: TWO_SHORT, Flags: PRIVATE, OWNER
	define('UNIT_FIELD_RANGED_ATTACK_POWER_MULTIPLIER', OBJECT_END + 0x007A); // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER
	define('UNIT_FIELD_MINRANGEDDAMAGE', OBJECT_END + 0x007B); // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER
	define('UNIT_FIELD_MAXRANGEDDAMAGE', OBJECT_END + 0x007C); // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER
	define('UNIT_FIELD_POWER_COST_MODIFIER', OBJECT_END + 0x007D); // Size: 7, Type: INT, Flags: PRIVATE, OWNER
	define('UNIT_FIELD_POWER_COST_MULTIPLIER', OBJECT_END + 0x0084); // Size: 7, Type: FLOAT, Flags: PRIVATE, OWNER
	define('UNIT_FIELD_MAXHEALTHMODIFIER', OBJECT_END + 0x008B); // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER
	define('UNIT_FIELD_HOVERHEIGHT', OBJECT_END + 0x008C); // Size: 1, Type: FLOAT, Flags: PUBLIC
	define('UNIT_FIELD_PADDING', OBJECT_END + 0x008D); // Size: 1, Type: INT, Flags: NONE
	define('UNIT_END', OBJECT_END + 0x008E);

	define('PLAYER_DUEL_ARBITER', UNIT_END + 0x0000);
	define('PLAYER_FLAGS', UNIT_END + 0x0002);
	define('PLAYER_GUILDID', UNIT_END + 0x0003);
	define('PLAYER_GUILDRANK', UNIT_END + 0x0004);
	define('PLAYER_BYTES', UNIT_END + 0x0005);
	define('PLAYER_BYTES_2', UNIT_END + 0x0006);
	define('PLAYER_BYTES_3', UNIT_END + 0x0007);
	define('PLAYER_DUEL_TEAM', UNIT_END + 0x0008);
	define('PLAYER_GUILD_TIMESTAMP', UNIT_END + 0x0009);
	define('PLAYER_QUEST_LOG_1_1', UNIT_END + 0x000A);
	define('PLAYER_QUEST_LOG_1_2', UNIT_END + 0x000B);
	define('PLAYER_QUEST_LOG_1_3', UNIT_END + 0x000C);
	define('PLAYER_QUEST_LOG_1_5', UNIT_END + 0x000E);
	define('PLAYER_QUEST_LOG_2_1', UNIT_END + 0x000F);
	define('PLAYER_QUEST_LOG_2_2', UNIT_END + 0x0010);
	define('PLAYER_QUEST_LOG_2_3', UNIT_END + 0x0011);
	define('PLAYER_QUEST_LOG_2_5', UNIT_END + 0x0013);
	define('PLAYER_QUEST_LOG_3_1', UNIT_END + 0x0014);
	define('PLAYER_QUEST_LOG_3_2', UNIT_END + 0x0015);
	define('PLAYER_QUEST_LOG_3_3', UNIT_END + 0x0016);
	define('PLAYER_QUEST_LOG_3_5', UNIT_END + 0x0018);
	define('PLAYER_QUEST_LOG_4_1', UNIT_END + 0x0019);
	define('PLAYER_QUEST_LOG_4_2', UNIT_END + 0x001A);
	define('PLAYER_QUEST_LOG_4_3', UNIT_END + 0x001B);
	define('PLAYER_QUEST_LOG_4_5', UNIT_END + 0x001D);
	define('PLAYER_QUEST_LOG_5_1', UNIT_END + 0x001E);
	define('PLAYER_QUEST_LOG_5_2', UNIT_END + 0x001F);
	define('PLAYER_QUEST_LOG_5_3', UNIT_END + 0x0020);
	define('PLAYER_QUEST_LOG_5_5', UNIT_END + 0x0022);
	define('PLAYER_QUEST_LOG_6_1', UNIT_END + 0x0023);
	define('PLAYER_QUEST_LOG_6_2', UNIT_END + 0x0024);
	define('PLAYER_QUEST_LOG_6_3', UNIT_END + 0x0025);
	define('PLAYER_QUEST_LOG_6_5', UNIT_END + 0x0027);
	define('PLAYER_QUEST_LOG_7_1', UNIT_END + 0x0028);
	define('PLAYER_QUEST_LOG_7_2', UNIT_END + 0x0029);
	define('PLAYER_QUEST_LOG_7_3', UNIT_END + 0x002A);
	define('PLAYER_QUEST_LOG_7_5', UNIT_END + 0x002C);
	define('PLAYER_QUEST_LOG_8_1', UNIT_END + 0x002D);
	define('PLAYER_QUEST_LOG_8_2', UNIT_END + 0x002E);
	define('PLAYER_QUEST_LOG_8_3', UNIT_END + 0x002F);
	define('PLAYER_QUEST_LOG_8_5', UNIT_END + 0x0031);
	define('PLAYER_QUEST_LOG_9_1', UNIT_END + 0x0032);
	define('PLAYER_QUEST_LOG_9_2', UNIT_END + 0x0033);
	define('PLAYER_QUEST_LOG_9_3', UNIT_END + 0x0034);
	define('PLAYER_QUEST_LOG_9_5', UNIT_END + 0x0036);
	define('PLAYER_QUEST_LOG_10_1', UNIT_END + 0x0037);
	define('PLAYER_QUEST_LOG_10_2', UNIT_END + 0x0038);
	define('PLAYER_QUEST_LOG_10_3', UNIT_END + 0x0039);
	define('PLAYER_QUEST_LOG_10_5', UNIT_END + 0x003B);
	define('PLAYER_QUEST_LOG_11_1', UNIT_END + 0x003C);
	define('PLAYER_QUEST_LOG_11_2', UNIT_END + 0x003D);
	define('PLAYER_QUEST_LOG_11_3', UNIT_END + 0x003E);
	define('PLAYER_QUEST_LOG_11_5', UNIT_END + 0x0040);
	define('PLAYER_QUEST_LOG_12_1', UNIT_END + 0x0041);
	define('PLAYER_QUEST_LOG_12_2', UNIT_END + 0x0042);
	define('PLAYER_QUEST_LOG_12_3', UNIT_END + 0x0043);
	define('PLAYER_QUEST_LOG_12_5', UNIT_END + 0x0045);
	define('PLAYER_QUEST_LOG_13_1', UNIT_END + 0x0046);
	define('PLAYER_QUEST_LOG_13_2', UNIT_END + 0x0047);
	define('PLAYER_QUEST_LOG_13_3', UNIT_END + 0x0048);
	define('PLAYER_QUEST_LOG_13_5', UNIT_END + 0x004A);
	define('PLAYER_QUEST_LOG_14_1', UNIT_END + 0x004B);
	define('PLAYER_QUEST_LOG_14_2', UNIT_END + 0x004C);
	define('PLAYER_QUEST_LOG_14_3', UNIT_END + 0x004D);
	define('PLAYER_QUEST_LOG_14_5', UNIT_END + 0x004F);
	define('PLAYER_QUEST_LOG_15_1', UNIT_END + 0x0050);
	define('PLAYER_QUEST_LOG_15_2', UNIT_END + 0x0051);
	define('PLAYER_QUEST_LOG_15_3', UNIT_END + 0x0052);
	define('PLAYER_QUEST_LOG_15_5', UNIT_END + 0x0054);
	define('PLAYER_QUEST_LOG_16_1', UNIT_END + 0x0055);
	define('PLAYER_QUEST_LOG_16_2', UNIT_END + 0x0056);
	define('PLAYER_QUEST_LOG_16_3', UNIT_END + 0x0057);
	define('PLAYER_QUEST_LOG_16_5', UNIT_END + 0x0059);
	define('PLAYER_QUEST_LOG_17_1', UNIT_END + 0x005A);
	define('PLAYER_QUEST_LOG_17_2', UNIT_END + 0x005B);
	define('PLAYER_QUEST_LOG_17_3', UNIT_END + 0x005C);
	define('PLAYER_QUEST_LOG_17_5', UNIT_END + 0x005E);
	define('PLAYER_QUEST_LOG_18_1', UNIT_END + 0x005F);
	define('PLAYER_QUEST_LOG_18_2', UNIT_END + 0x0060);
	define('PLAYER_QUEST_LOG_18_3', UNIT_END + 0x0061);
	define('PLAYER_QUEST_LOG_18_5', UNIT_END + 0x0063);
	define('PLAYER_QUEST_LOG_19_1', UNIT_END + 0x0064);
	define('PLAYER_QUEST_LOG_19_2', UNIT_END + 0x0065);
	define('PLAYER_QUEST_LOG_19_3', UNIT_END + 0x0066);
	define('PLAYER_QUEST_LOG_19_5', UNIT_END + 0x0068);
	define('PLAYER_QUEST_LOG_20_1', UNIT_END + 0x0069);
	define('PLAYER_QUEST_LOG_20_2', UNIT_END + 0x006A);
	define('PLAYER_QUEST_LOG_20_3', UNIT_END + 0x006B);
	define('PLAYER_QUEST_LOG_20_5', UNIT_END + 0x006D);
	define('PLAYER_QUEST_LOG_21_1', UNIT_END + 0x006E);
	define('PLAYER_QUEST_LOG_21_2', UNIT_END + 0x006F);
	define('PLAYER_QUEST_LOG_21_3', UNIT_END + 0x0070);
	define('PLAYER_QUEST_LOG_21_5', UNIT_END + 0x0072);
	define('PLAYER_QUEST_LOG_22_1', UNIT_END + 0x0073);
	define('PLAYER_QUEST_LOG_22_2', UNIT_END + 0x0074);
	define('PLAYER_QUEST_LOG_22_3', UNIT_END + 0x0075);
	define('PLAYER_QUEST_LOG_22_5', UNIT_END + 0x0077);
	define('PLAYER_QUEST_LOG_23_1', UNIT_END + 0x0078);
	define('PLAYER_QUEST_LOG_23_2', UNIT_END + 0x0079);
	define('PLAYER_QUEST_LOG_23_3', UNIT_END + 0x007A);
	define('PLAYER_QUEST_LOG_23_5', UNIT_END + 0x007C);
	define('PLAYER_QUEST_LOG_24_1', UNIT_END + 0x007D);
	define('PLAYER_QUEST_LOG_24_2', UNIT_END + 0x007E);
	define('PLAYER_QUEST_LOG_24_3', UNIT_END + 0x007F);
	define('PLAYER_QUEST_LOG_24_5', UNIT_END + 0x0081);
	define('PLAYER_QUEST_LOG_25_1', UNIT_END + 0x0082);
	define('PLAYER_QUEST_LOG_25_2', UNIT_END + 0x0083);
	define('PLAYER_QUEST_LOG_25_3', UNIT_END + 0x0084);
	define('PLAYER_QUEST_LOG_25_5', UNIT_END + 0x0086);
	define('PLAYER_VISIBLE_ITEM_1_ENTRYID', 0x0001);
	define('PLAYER_VISIBLE_ITEM_1_ENCHANTMENT', UNIT_END + 0x0088);
	define('PLAYER_VISIBLE_ITEM_2_ENTRYID', UNIT_END + 0x0089);
	define('PLAYER_VISIBLE_ITEM_2_ENCHANTMENT', UNIT_END + 0x008A);
	define('PLAYER_VISIBLE_ITEM_3_ENTRYID', UNIT_END + 0x008B);
	define('PLAYER_VISIBLE_ITEM_3_ENCHANTMENT', UNIT_END + 0x008C);
	define('PLAYER_VISIBLE_ITEM_4_ENTRYID', UNIT_END + 0x008D);
	define('PLAYER_VISIBLE_ITEM_4_ENCHANTMENT', UNIT_END + 0x008E);
	define('PLAYER_VISIBLE_ITEM_5_ENTRYID', UNIT_END + 0x008F);
	define('PLAYER_VISIBLE_ITEM_5_ENCHANTMENT', UNIT_END + 0x0090);
	define('PLAYER_VISIBLE_ITEM_6_ENTRYID', UNIT_END + 0x0091);
	define('PLAYER_VISIBLE_ITEM_6_ENCHANTMENT', UNIT_END + 0x0092);
	define('PLAYER_VISIBLE_ITEM_7_ENTRYID', UNIT_END + 0x0093);
	define('PLAYER_VISIBLE_ITEM_7_ENCHANTMENT', UNIT_END + 0x0094);
	define('PLAYER_VISIBLE_ITEM_8_ENTRYID', UNIT_END + 0x0095);
	define('PLAYER_VISIBLE_ITEM_8_ENCHANTMENT', UNIT_END + 0x0096);
	define('PLAYER_VISIBLE_ITEM_9_ENTRYID', UNIT_END + 0x0097);
	define('PLAYER_VISIBLE_ITEM_9_ENCHANTMENT', UNIT_END + 0x0098);
	define('PLAYER_VISIBLE_ITEM_10_ENTRYID', UNIT_END + 0x0099);
	define('PLAYER_VISIBLE_ITEM_10_ENCHANTMENT', UNIT_END + 0x009A);
	define('PLAYER_VISIBLE_ITEM_11_ENTRYID', UNIT_END + 0x009B);
	define('PLAYER_VISIBLE_ITEM_11_ENCHANTMENT', UNIT_END + 0x009C);
	define('PLAYER_VISIBLE_ITEM_12_ENTRYID', UNIT_END + 0x009D);
	define('PLAYER_VISIBLE_ITEM_12_ENCHANTMENT', UNIT_END + 0x009E);
	define('PLAYER_VISIBLE_ITEM_13_ENTRYID', UNIT_END + 0x009F);
	define('PLAYER_VISIBLE_ITEM_13_ENCHANTMENT', UNIT_END + 0x00A0);
	define('PLAYER_VISIBLE_ITEM_14_ENTRYID', UNIT_END + 0x00A1);
	define('PLAYER_VISIBLE_ITEM_14_ENCHANTMENT', UNIT_END + 0x00A2);
	define('PLAYER_VISIBLE_ITEM_15_ENTRYID', UNIT_END + 0x00A3);
	define('PLAYER_VISIBLE_ITEM_15_ENCHANTMENT', UNIT_END + 0x00A4);
	define('PLAYER_VISIBLE_ITEM_16_ENTRYID', UNIT_END + 0x00A5);
	define('PLAYER_VISIBLE_ITEM_16_ENCHANTMENT', UNIT_END + 0x00A6);
	define('PLAYER_VISIBLE_ITEM_17_ENTRYID', UNIT_END + 0x00A7);
	define('PLAYER_VISIBLE_ITEM_17_ENCHANTMENT', UNIT_END + 0x00A8);
	define('PLAYER_VISIBLE_ITEM_18_ENTRYID', UNIT_END + 0x00A9);
	define('PLAYER_VISIBLE_ITEM_18_ENCHANTMENT', UNIT_END + 0x00AA);
	define('PLAYER_VISIBLE_ITEM_19_ENTRYID', UNIT_END + 0x00AB);
	define('PLAYER_VISIBLE_ITEM_19_ENCHANTMENT', UNIT_END + 0x00AC);
	define('PLAYER_CHOSEN_TITLE', UNIT_END + 0x00AD);
	define('PLAYER_FAKE_INEBRIATION', UNIT_END + 0x00AE);
	define('PLAYER_FIELD_PAD_0', UNIT_END + 0x00AF);
	define('PLAYER_FIELD_INV_SLOT_HEAD', 0);
	define('PLAYER_FIELD_PACK_SLOT_1', UNIT_END + 0x00DE);
	define('PLAYER_FIELD_BANK_SLOT_1', UNIT_END + 0x00FE);
	define('PLAYER_FIELD_BANKBAG_SLOT_1', UNIT_END + 0x0136);
	define('PLAYER_FIELD_VENDORBUYBACK_SLOT_1', UNIT_END + 0x0144);
	define('PLAYER_FIELD_KEYRING_SLOT_1', UNIT_END + 0x015C);
	define('PLAYER_FIELD_CURRENCYTOKEN_SLOT_1', UNIT_END + 0x019C);
	define('PLAYER_FARSIGHT', UNIT_END + 0x01DC);
	define('PLAYER__FIELD_KNOWN_TITLES', UNIT_END + 0x01DE);
	define('PLAYER__FIELD_KNOWN_TITLES1', UNIT_END + 0x01E0);
	define('PLAYER__FIELD_KNOWN_TITLES2', UNIT_END + 0x01E2);
	define('PLAYER_FIELD_KNOWN_CURRENCIES', UNIT_END + 0x01E4);
	define('PLAYER_XP', UNIT_END + 0x01E6);
	define('PLAYER_NEXT_LEVEL_XP', UNIT_END + 0x01E7);
	define('PLAYER_SKILL_INFO_1_1', UNIT_END + 0x01E8);
	define('PLAYER_CHARACTER_POINTS1', UNIT_END + 0x0368);
	define('PLAYER_CHARACTER_POINTS2', UNIT_END + 0x0369);
	define('PLAYER_TRACK_CREATURES', UNIT_END + 0x036A);
	define('PLAYER_TRACK_RESOURCES', UNIT_END + 0x036B);
	define('PLAYER_BLOCK_PERCENTAGE', UNIT_END + 0x036C);
	define('PLAYER_DODGE_PERCENTAGE', UNIT_END + 0x036D);
	define('PLAYER_PARRY_PERCENTAGE', UNIT_END + 0x036E);
	define('PLAYER_EXPERTISE', UNIT_END + 0x036F);
	define('PLAYER_OFFHAND_EXPERTISE', UNIT_END + 0x0370);
	define('PLAYER_CRIT_PERCENTAGE', UNIT_END + 0x0371);
	define('PLAYER_RANGED_CRIT_PERCENTAGE', UNIT_END + 0x0372);
	define('PLAYER_OFFHAND_CRIT_PERCENTAGE', UNIT_END + 0x0373);
	define('PLAYER_SPELL_CRIT_PERCENTAGE', UNIT_END + 0x0374);
	define('PLAYER_SHIELD_BLOCK', UNIT_END + 0x037B);
	define('PLAYER_SHIELD_BLOCK_CRIT_PERCENTAGE', UNIT_END + 0x037C);
	define('PLAYER_EXPLORED_ZONES_1', UNIT_END + 0x037D);
	define('PLAYER_REST_STATE_EXPERIENCE', UNIT_END + 0x03FD);
	define('PLAYER_FIELD_COINAGE', UNIT_END + 0x03FE);
	define('PLAYER_FIELD_MOD_DAMAGE_DONE_POS', UNIT_END + 0x03FF);
	define('PLAYER_FIELD_MOD_DAMAGE_DONE_NEG', UNIT_END + 0x0406);
	define('PLAYER_FIELD_MOD_DAMAGE_DONE_PCT', UNIT_END + 0x040D);
	define('PLAYER_FIELD_MOD_HEALING_DONE_POS', UNIT_END + 0x0414);
	define('PLAYER_FIELD_MOD_HEALING_PCT', UNIT_END + 0x0415);
	define('PLAYER_FIELD_MOD_HEALING_DONE_PCT', UNIT_END + 0x0416);
	define('PLAYER_FIELD_MOD_TARGET_RESISTANCE', UNIT_END + 0x0417);
	define('PLAYER_FIELD_MOD_TARGET_PHYSICAL_RESISTANCE', UNIT_END + 0x0418);
	define('PLAYER_FIELD_BYTES', UNIT_END + 0x0419);
	define('PLAYER_AMMO_ID', UNIT_END + 0x041A);
	define('PLAYER_SELF_RES_SPELL', UNIT_END + 0x041B);
	define('PLAYER_FIELD_PVP_MEDALS', UNIT_END + 0x041C);
	define('PLAYER_FIELD_BUYBACK_PRICE_1', UNIT_END + 0x041D);
	define('PLAYER_FIELD_BUYBACK_TIMESTAMP_1', UNIT_END + 0x0429);
	define('PLAYER_FIELD_KILLS', UNIT_END + 0x0435);
	define('PLAYER_FIELD_TODAY_CONTRIBUTION', UNIT_END + 0x0436);
	define('PLAYER_FIELD_YESTERDAY_CONTRIBUTION', UNIT_END + 0x0437);
	define('PLAYER_FIELD_LIFETIME_HONORBALE_KILLS', UNIT_END + 0x0438);
	define('PLAYER_FIELD_BYTES2', UNIT_END + 0x0439);
	define('PLAYER_FIELD_WATCHED_FACTION_INDEX', UNIT_END + 0x043A);
	define('PLAYER_FIELD_COMBAT_RATING', UNIT_END + 0x043B);
	define('PLAYER_FIELD_ARENA_TEAM_INFO_1_1', UNIT_END + 0x0454);
	define('PLAYER_FIELD_HONOR_CURRENCY', UNIT_END + 0x0469);
	define('PLAYER_FIELD_ARENA_CURRENCY', UNIT_END + 0x046A);
	define('PLAYER_FIELD_MAX_LEVEL', UNIT_END + 0x046B);
	define('PLAYER_FIELD_DAILY_QUESTS_1', UNIT_END + 0x046C);
	define('PLAYER_RUNE_REGEN_1', UNIT_END + 0x0485);
	define('PLAYER_NO_REAGENT_COST_1', UNIT_END + 0x0489);
	define('PLAYER_FIELD_GLYPH_SLOTS_1', UNIT_END + 0x048C);
	define('PLAYER_FIELD_GLYPHS_1', UNIT_END + 0x0492);
	define('PLAYER_GLYPHS_ENABLED', UNIT_END + 0x0498);
	define('PLAYER_FIELD_PADDING', UNIT_END + 0x0499);
	define('PLAYER_END', UNIT_END + 0x049A);
	
	//=====================================
	define('PLAYER_HOLY_SPELL_CRIT_PERCENTAGE', PLAYER_SPELL_CRIT_PERCENTAGE+1);	//
	define('PLAYER_FIRE_SPELL_CRIT_PERCENTAGE', PLAYER_SPELL_CRIT_PERCENTAGE+2);	//
	define('PLAYER_NATURE_SPELL_CRIT_PERCENTAGE', PLAYER_SPELL_CRIT_PERCENTAGE+3);	//
	define('PLAYER_FROST_SPELL_CRIT_PERCENTAGE', PLAYER_SPELL_CRIT_PERCENTAGE+4);	//
	define('PLAYER_SHADOW_SPELL_CRIT_PERCENTAGE', PLAYER_SPELL_CRIT_PERCENTAGE+5);	//
	define('PLAYER_ARCANE_SPELL_CRIT_PERCENTAGE', PLAYER_SPELL_CRIT_PERCENTAGE+6);	//
	
	define('PLAYER_FIELD_ARENA_TEAM_ID_2v2', PLAYER_FIELD_ARENA_TEAM_INFO_1_1);	//
	define('PLAYER_FIELD_ARENA_TEAM_ID_3v3', PLAYER_FIELD_ARENA_TEAM_INFO_1_1+6);	//
	define('PLAYER_FIELD_ARENA_TEAM_ID_5v5', PLAYER_FIELD_ARENA_TEAM_INFO_1_1+12);	//
	
	define('PLAYER_FIELD_ALL_WEAPONS_SKILL_RATING', PLAYER_FIELD_COMBAT_RATING);	// CR_WEAPON_SKILL
	define('PLAYER_FIELD_DEFENCE_RATING', PLAYER_FIELD_COMBAT_RATING+1);	// CR_DEFENSE_SKILL
	define('PLAYER_FIELD_DODGE_RATING', PLAYER_FIELD_COMBAT_RATING+2);	// CR_DODGE
	define('PLAYER_FIELD_PARRY_RATING', PLAYER_FIELD_COMBAT_RATING+3);	// CR_PARRY
	define('PLAYER_FIELD_BLOCK_RATING', PLAYER_FIELD_COMBAT_RATING+4);	// CR_BLOCK
	define('PLAYER_FIELD_MELEE_HIT_RATING', PLAYER_FIELD_COMBAT_RATING+5);	// CR_HIT_MELEE
	define('PLAYER_FIELD_RANGED_HIT_RATING', PLAYER_FIELD_COMBAT_RATING+6);	// CR_HIT_RANGED
	define('PLAYER_FIELD_SPELL_HIT_RATING', PLAYER_FIELD_COMBAT_RATING+7);	// CR_HIT_SPELL
	define('PLAYER_FIELD_MELEE_CRIT_RATING', PLAYER_FIELD_COMBAT_RATING+8);	// CR_CRIT_MELEE
	define('PLAYER_FIELD_RANGED_CRIT_RATING', PLAYER_FIELD_COMBAT_RATING+9);	// CR_CRIT_RANGED
	define('PLAYER_FIELD_SPELL_CRIT_RATING', PLAYER_FIELD_COMBAT_RATING+10);	// CR_CRIT_SPELL
	define('PLAYER_FIELD_TAKEN_MELEE_HIT_RATING', PLAYER_FIELD_COMBAT_RATING+11);	// CR_HIT_TAKEN_MELEE
	define('PLAYER_FIELD_TAKEN_RANGED_HIT_RATING', PLAYER_FIELD_COMBAT_RATING+12);	// CR_HIT_TAKEN_RANGED
	define('PLAYER_FIELD_TAKEN_SPELL_HIT_RATING', PLAYER_FIELD_COMBAT_RATING+13);	// CR_HIT_TAKEN_SPELL
	define('PLAYER_FIELD_CRIT_TAKEN_MELEE_RATING', PLAYER_FIELD_COMBAT_RATING+14);	// CR_CRIT_TAKEN_MELEE
	define('PLAYER_FIELD_CRIT_TAKEN_RANGED_RATING', PLAYER_FIELD_COMBAT_RATING+15);	// CR_CRIT_TAKEN_RANGED
	define('PLAYER_FIELD_CRIT_TAKEN_SPELL_RATING', PLAYER_FIELD_COMBAT_RATING+16);	// CR_CRIT_TAKEN_SPELL
	define('PLAYER_FIELD_MELEE_HASTE_RATING', PLAYER_FIELD_COMBAT_RATING+17);	// CR_HASTE_MELEE
	define('PLAYER_FIELD_RANGED_HASTE_RATING', PLAYER_FIELD_COMBAT_RATING+18);	// CR_HASTE_RANGED
	define('PLAYER_FIELD_SPELL_HASTE_RATING', PLAYER_FIELD_COMBAT_RATING+19);	// CR_HASTE_SPELL
	define('PLAYER_FIELD_MELEE_WEAPON_SKILL_RATING', PLAYER_FIELD_COMBAT_RATING+20);	// CR_WEAPON_SKILL_MAINHAND
	define('PLAYER_FIELD_OFFHAND_WEAPON_SKILL_RATING', PLAYER_FIELD_COMBAT_RATING+21);	// CR_WEAPON_SKILL_OFFHAND
	define('PLAYER_FIELD_RANGED_WEAPON_SKILL_RATING', PLAYER_FIELD_COMBAT_RATING+22);	// CR_WEAPON_SKILL_RANGED
	define('PLAYER_FIELD_EXPERTISE_RATING', PLAYER_FIELD_COMBAT_RATING+23);	// CR_EXPERTISE
	
	//*************************************************************
	
	define('PLAYER_VISIBLE_ITEM_HEAD',PLAYER_VISIBLE_ITEM_1_ENTRYID); // 12 1 1
	define('PLAYER_VISIBLE_ITEM_NECK',PLAYER_VISIBLE_ITEM_2_ENTRYID); // 12 1 1
	define('PLAYER_VISIBLE_ITEM_SHOULDER',PLAYER_VISIBLE_ITEM_3_ENTRYID); // 12 1 1
	define('PLAYER_VISIBLE_ITEM_SHIRT',PLAYER_VISIBLE_ITEM_4_ENTRYID); // 12 1 1
	define('PLAYER_VISIBLE_ITEM_CHEST',PLAYER_VISIBLE_ITEM_5_ENTRYID); // 12 1 1
	define('PLAYER_VISIBLE_ITEM_BELT',PLAYER_VISIBLE_ITEM_6_ENTRYID); // 12 1 1
	define('PLAYER_VISIBLE_ITEM_LEGS',PLAYER_VISIBLE_ITEM_7_ENTRYID); // 12 1 1
	define('PLAYER_VISIBLE_ITEM_FEET',PLAYER_VISIBLE_ITEM_8_ENTRYID); // 12 1 1
	define('PLAYER_VISIBLE_ITEM_WRIST',PLAYER_VISIBLE_ITEM_9_ENTRYID); // 12 1 1
	define('PLAYER_VISIBLE_ITEM_GLOVES',PLAYER_VISIBLE_ITEM_10_ENTRYID); // 12 1 1
	define('PLAYER_VISIBLE_ITEM_FINGER1',PLAYER_VISIBLE_ITEM_11_ENTRYID); // 12 1 1
	define('PLAYER_VISIBLE_ITEM_FINGER2',PLAYER_VISIBLE_ITEM_12_ENTRYID); // 12 1 1
	define('PLAYER_VISIBLE_ITEM_TRINKET1',PLAYER_VISIBLE_ITEM_13_ENTRYID); // 12 1 1
	define('PLAYER_VISIBLE_ITEM_TRINKET2',PLAYER_VISIBLE_ITEM_14_ENTRYID); // 12 1 1
	define('PLAYER_VISIBLE_ITEM_BACK',PLAYER_VISIBLE_ITEM_15_ENTRYID); // 12 1 1
	define('PLAYER_VISIBLE_ITEM_MAIN_HAND',PLAYER_VISIBLE_ITEM_16_ENTRYID); // 12 1 1
	define('PLAYER_VISIBLE_ITEM_OFF_HAND',PLAYER_VISIBLE_ITEM_17_ENTRYID); // 12 1 1
	define('PLAYER_VISIBLE_ITEM_RANGED',PLAYER_VISIBLE_ITEM_18_ENTRYID); // 12 1 1
	define('PLAYER_VISIBLE_ITEM_TABARD',PLAYER_VISIBLE_ITEM_19_ENTRYID); // 12 1 1
	
	define('PLAYER_SLOT_ITEM_HEAD',PLAYER_FIELD_INV_SLOT_HEAD);
	define('PLAYER_SLOT_ITEM_NECK',PLAYER_FIELD_INV_SLOT_HEAD+2);
	define('PLAYER_SLOT_ITEM_SHOULDER',PLAYER_FIELD_INV_SLOT_HEAD+4);
	define('PLAYER_SLOT_ITEM_SHIRT',PLAYER_FIELD_INV_SLOT_HEAD+6);
	define('PLAYER_SLOT_ITEM_CHEST',PLAYER_FIELD_INV_SLOT_HEAD+8);
	define('PLAYER_SLOT_ITEM_BELT',PLAYER_FIELD_INV_SLOT_HEAD+10);
	define('PLAYER_SLOT_ITEM_LEGS',PLAYER_FIELD_INV_SLOT_HEAD+12);
	define('PLAYER_SLOT_ITEM_FEET',PLAYER_FIELD_INV_SLOT_HEAD+14);
	define('PLAYER_SLOT_ITEM_WRIST',PLAYER_FIELD_INV_SLOT_HEAD+16);
	define('PLAYER_SLOT_ITEM_GLOVES',PLAYER_FIELD_INV_SLOT_HEAD+18);
	define('PLAYER_SLOT_ITEM_FINGER1',PLAYER_FIELD_INV_SLOT_HEAD+20);
	define('PLAYER_SLOT_ITEM_FINGER2',PLAYER_FIELD_INV_SLOT_HEAD+22);
	define('PLAYER_SLOT_ITEM_TRINKET1',PLAYER_FIELD_INV_SLOT_HEAD+24);
	define('PLAYER_SLOT_ITEM_TRINKET2',PLAYER_FIELD_INV_SLOT_HEAD+26);
	define('PLAYER_SLOT_ITEM_BACK',PLAYER_FIELD_INV_SLOT_HEAD+28);
	define('PLAYER_SLOT_ITEM_MAIN_HAND',PLAYER_FIELD_INV_SLOT_HEAD+30);
	define('PLAYER_SLOT_ITEM_OFF_HAND',PLAYER_FIELD_INV_SLOT_HEAD+32);
	define('PLAYER_SLOT_ITEM_RANGED',PLAYER_FIELD_INV_SLOT_HEAD+34);
	define('PLAYER_SLOT_ITEM_TABARD',PLAYER_FIELD_INV_SLOT_HEAD+36);
	
	define('EQUIPMENT_SLOT_START',    0);
	define('EQUIPMENT_SLOT_HEAD',     0);
	define('EQUIPMENT_SLOT_NECK',     1);
	define('EQUIPMENT_SLOT_SHOULDERS',2);
	define('EQUIPMENT_SLOT_BODY',     3);
	define('EQUIPMENT_SLOT_CHEST',    4);
	define('EQUIPMENT_SLOT_WAIST',    5);
	define('EQUIPMENT_SLOT_LEGS',     6);
	define('EQUIPMENT_SLOT_FEET',     7);
	define('EQUIPMENT_SLOT_WRISTS',   8);
	define('EQUIPMENT_SLOT_HANDS',    9);
	define('EQUIPMENT_SLOT_FINGER1', 10);
	define('EQUIPMENT_SLOT_FINGER2', 11);
	define('EQUIPMENT_SLOT_TRINKET1',12);
	define('EQUIPMENT_SLOT_TRINKET2',13);
	define('EQUIPMENT_SLOT_BACK',    14);
	define('EQUIPMENT_SLOT_MAINHAND',15);
	define('EQUIPMENT_SLOT_OFFHAND', 16);
	define('EQUIPMENT_SLOT_RANGED',  17);
	define('EQUIPMENT_SLOT_TABARD',  18);
	define('EQUIPMENT_SLOT_END',     19);
	
	define('INVENTORY_SLOT_BAG_START', 19);
	define('INVENTORY_SLOT_BAG_END',   23);
	
	define('INVENTORY_SLOT_ITEM_START',23);
	define('INVENTORY_SLOT_ITEM_END',39);
	
	define('BANK_SLOT_ITEM_START',   39);
	define('BANK_SLOT_ITEM_END',     67);
	
	define('BANK_SLOT_BAG_START',    67);
	define('BANK_SLOT_BAG_END',      74);
	
	define('BUYBACK_SLOT_START',     74);
	define('BUYBACK_SLOT_END',       86);
	
	define('KEYRING_SLOT_START',     86);
	define('KEYRING_SLOT_END',      118);
	
	define('INVENTORY_SLOT_BAG_0',  255);
	
	$gPlayerDataFields = array(
	OBJECT_END + 0x0000=>'UNIT_FIELD_CHARM',
	OBJECT_END + 0x0002=>'UNIT_FIELD_SUMMON',
	OBJECT_END + 0x0004=>'UNIT_FIELD_CRITTER',
	OBJECT_END + 0x0006=>'UNIT_FIELD_CHARMEDBY',
	OBJECT_END + 0x0008=>'UNIT_FIELD_SUMMONEDBY',
	OBJECT_END + 0x000A=>'UNIT_FIELD_CREATEDBY',
	OBJECT_END + 0x000C=>'UNIT_FIELD_TARGET',
	OBJECT_END + 0x000E=>'UNIT_FIELD_CHANNEL_OBJECT',
	OBJECT_END + 0x0010=>'UNIT_FIELD_BYTES_0',
	OBJECT_END + 0x0011=>'UNIT_FIELD_HEALTH',
	OBJECT_END + 0x0012=>'UNIT_FIELD_POWER1',
	OBJECT_END + 0x0013=>'UNIT_FIELD_POWER2',
	OBJECT_END + 0x0014=>'UNIT_FIELD_POWER3',
	OBJECT_END + 0x0015=>'UNIT_FIELD_POWER4',
	OBJECT_END + 0x0016=>'UNIT_FIELD_POWER5',
	OBJECT_END + 0x0017=>'UNIT_FIELD_POWER6',
	OBJECT_END + 0x0018=>'UNIT_FIELD_POWER7',
	OBJECT_END + 0x0019=>'UNIT_FIELD_MAXHEALTH',
	OBJECT_END + 0x001A=>'UNIT_FIELD_MAXPOWER1',
	OBJECT_END + 0x001B=>'UNIT_FIELD_MAXPOWER2',
	OBJECT_END + 0x001C=>'UNIT_FIELD_MAXPOWER3',
	OBJECT_END + 0x001D=>'UNIT_FIELD_MAXPOWER4',
	OBJECT_END + 0x001E=>'UNIT_FIELD_MAXPOWER5',
	OBJECT_END + 0x001F=>'UNIT_FIELD_MAXPOWER6',
	OBJECT_END + 0x0020=>'UNIT_FIELD_MAXPOWER7',
	OBJECT_END + 0x0021=>'UNIT_FIELD_POWER_REGEN_FLAT_MODIFIER',
	OBJECT_END + 0x0028=>'UNIT_FIELD_POWER_REGEN_INTERRUPTED_FLAT_MODIFIER',
	OBJECT_END + 0x002F=>'UNIT_FIELD_LEVEL',
	OBJECT_END + 0x0030=>'UNIT_FIELD_FACTIONTEMPLATE',
	OBJECT_END + 0x0031=>'UNIT_VIRTUAL_ITEM_SLOT_ID',
	OBJECT_END + 0x0034=>'UNIT_FIELD_FLAGS',
	OBJECT_END + 0x0035=>'UNIT_FIELD_FLAGS_2',
	OBJECT_END + 0x0036=>'UNIT_FIELD_AURASTATE',
	OBJECT_END + 0x0037=>'UNIT_FIELD_BASEATTACKTIME',
	OBJECT_END + 0x0039=>'UNIT_FIELD_RANGEDATTACKTIME',
	OBJECT_END + 0x003A=>'UNIT_FIELD_BOUNDINGRADIUS',
	OBJECT_END + 0x003B=>'UNIT_FIELD_COMBATREACH',
	OBJECT_END + 0x003C=>'UNIT_FIELD_DISPLAYID',
	OBJECT_END + 0x003D=>'UNIT_FIELD_NATIVEDISPLAYID',
	OBJECT_END + 0x003E=>'UNIT_FIELD_MOUNTDISPLAYID',
	OBJECT_END + 0x003F=>'UNIT_FIELD_MINDAMAGE',
	OBJECT_END + 0x0040=>'UNIT_FIELD_MAXDAMAGE',
	OBJECT_END + 0x0041=>'UNIT_FIELD_MINOFFHANDDAMAGE',
	OBJECT_END + 0x0042=>'UNIT_FIELD_MAXOFFHANDDAMAGE',
	OBJECT_END + 0x0043=>'UNIT_FIELD_BYTES_1',
	OBJECT_END + 0x0044=>'UNIT_FIELD_PETNUMBER',
	OBJECT_END + 0x0045=>'UNIT_FIELD_PET_NAME_TIMESTAMP',
	OBJECT_END + 0x0046=>'UNIT_FIELD_PETEXPERIENCE',
	OBJECT_END + 0x0047=>'UNIT_FIELD_PETNEXTLEVELEXP',
	OBJECT_END + 0x0048=>'UNIT_DYNAMIC_FLAGS',
	OBJECT_END + 0x0049=>'UNIT_CHANNEL_SPELL',
	OBJECT_END + 0x004A=>'UNIT_MOD_CAST_SPEED',
	OBJECT_END + 0x004B=>'UNIT_CREATED_BY_SPELL',
	OBJECT_END + 0x004C=>'UNIT_NPC_FLAGS',
	OBJECT_END + 0x004D=>'UNIT_NPC_EMOTESTATE',
	OBJECT_END + 0x004E=>'UNIT_FIELD_STAT0',
	OBJECT_END + 0x004F=>'UNIT_FIELD_STAT1',
	OBJECT_END + 0x0050=>'UNIT_FIELD_STAT2',
	OBJECT_END + 0x0051=>'UNIT_FIELD_STAT3',
	OBJECT_END + 0x0052=>'UNIT_FIELD_STAT4',
	OBJECT_END + 0x0053=>'UNIT_FIELD_POSSTAT0',
	OBJECT_END + 0x0054=>'UNIT_FIELD_POSSTAT1',
	OBJECT_END + 0x0055=>'UNIT_FIELD_POSSTAT2',
	OBJECT_END + 0x0056=>'UNIT_FIELD_POSSTAT3',
	OBJECT_END + 0x0057=>'UNIT_FIELD_POSSTAT4',
	OBJECT_END + 0x0058=>'UNIT_FIELD_NEGSTAT0',
	OBJECT_END + 0x0059=>'UNIT_FIELD_NEGSTAT1',
	OBJECT_END + 0x005A=>'UNIT_FIELD_NEGSTAT2',
	OBJECT_END + 0x005B=>'UNIT_FIELD_NEGSTAT3',
	OBJECT_END + 0x005C=>'UNIT_FIELD_NEGSTAT4',
	OBJECT_END + 0x005D=>'UNIT_FIELD_RESISTANCES',
	OBJECT_END + 0x0064=>'UNIT_FIELD_RESISTANCEBUFFMODSPOSITIVE',
	OBJECT_END + 0x006B=>'UNIT_FIELD_RESISTANCEBUFFMODSNEGATIVE',
	OBJECT_END + 0x0072=>'UNIT_FIELD_BASE_MANA',
	OBJECT_END + 0x0073=>'UNIT_FIELD_BASE_HEALTH',
	OBJECT_END + 0x0074=>'UNIT_FIELD_BYTES_2',
	OBJECT_END + 0x0075=>'UNIT_FIELD_ATTACK_POWER',
	OBJECT_END + 0x0076=>'UNIT_FIELD_ATTACK_POWER_MODS',
	OBJECT_END + 0x0077=>'UNIT_FIELD_ATTACK_POWER_MULTIPLIER',
	OBJECT_END + 0x0078=>'UNIT_FIELD_RANGED_ATTACK_POWER',
	OBJECT_END + 0x0079=>'UNIT_FIELD_RANGED_ATTACK_POWER_MODS',
	OBJECT_END + 0x007A=>'UNIT_FIELD_RANGED_ATTACK_POWER_MULTIPLIER',
	OBJECT_END + 0x007B=>'UNIT_FIELD_MINRANGEDDAMAGE',
	OBJECT_END + 0x007C=>'UNIT_FIELD_MAXRANGEDDAMAGE',
	OBJECT_END + 0x007D=>'UNIT_FIELD_POWER_COST_MODIFIER',
	OBJECT_END + 0x0084=>'UNIT_FIELD_POWER_COST_MULTIPLIER',
	OBJECT_END + 0x008B=>'UNIT_FIELD_MAXHEALTHMODIFIER',
	OBJECT_END + 0x008C=>'UNIT_FIELD_HOVERHEIGHT',
	OBJECT_END + 0x008D=>'UNIT_FIELD_PADDING',
	OBJECT_END + 0x008E=>'UNIT_END',
	
	UNIT_END + 0x0000=>'PLAYER_DUEL_ARBITER',
	UNIT_END + 0x0002=>'PLAYER_FLAGS',
	UNIT_END + 0x0003=>'PLAYER_GUILDID',
	UNIT_END + 0x0004=>'PLAYER_GUILDRANK',
	UNIT_END + 0x0005=>'PLAYER_BYTES',
	UNIT_END + 0x0006=>'PLAYER_BYTES_2',
	UNIT_END + 0x0007=>'PLAYER_BYTES_3',
	UNIT_END + 0x0008=>'PLAYER_DUEL_TEAM',
	UNIT_END + 0x0009=>'PLAYER_GUILD_TIMESTAMP',
	UNIT_END + 0x000A=>'PLAYER_QUEST_LOG_1_1',
	UNIT_END + 0x000B=>'PLAYER_QUEST_LOG_1_2',
	UNIT_END + 0x000C=>'PLAYER_QUEST_LOG_1_3',
	UNIT_END + 0x000E=>'PLAYER_QUEST_LOG_1_5',
	UNIT_END + 0x000F=>'PLAYER_QUEST_LOG_2_1',
	UNIT_END + 0x0010=>'PLAYER_QUEST_LOG_2_2',
	UNIT_END + 0x0011=>'PLAYER_QUEST_LOG_2_3',
	UNIT_END + 0x0013=>'PLAYER_QUEST_LOG_2_5',
	UNIT_END + 0x0014=>'PLAYER_QUEST_LOG_3_1',
	UNIT_END + 0x0015=>'PLAYER_QUEST_LOG_3_2',
	UNIT_END + 0x0016=>'PLAYER_QUEST_LOG_3_3',
	UNIT_END + 0x0018=>'PLAYER_QUEST_LOG_3_5',
	UNIT_END + 0x0019=>'PLAYER_QUEST_LOG_4_1',
	UNIT_END + 0x001A=>'PLAYER_QUEST_LOG_4_2',
	UNIT_END + 0x001B=>'PLAYER_QUEST_LOG_4_3',
	UNIT_END + 0x001D=>'PLAYER_QUEST_LOG_4_5',
	UNIT_END + 0x001E=>'PLAYER_QUEST_LOG_5_1',
	UNIT_END + 0x001F=>'PLAYER_QUEST_LOG_5_2',
	UNIT_END + 0x0020=>'PLAYER_QUEST_LOG_5_3',
	UNIT_END + 0x0022=>'PLAYER_QUEST_LOG_5_5',
	UNIT_END + 0x0023=>'PLAYER_QUEST_LOG_6_1',
	UNIT_END + 0x0024=>'PLAYER_QUEST_LOG_6_2',
	UNIT_END + 0x0025=>'PLAYER_QUEST_LOG_6_3',
	UNIT_END + 0x0027=>'PLAYER_QUEST_LOG_6_5',
	UNIT_END + 0x0028=>'PLAYER_QUEST_LOG_7_1',
	UNIT_END + 0x0029=>'PLAYER_QUEST_LOG_7_2',
	UNIT_END + 0x002A=>'PLAYER_QUEST_LOG_7_3',
	UNIT_END + 0x002C=>'PLAYER_QUEST_LOG_7_5',
	UNIT_END + 0x002D=>'PLAYER_QUEST_LOG_8_1',
	UNIT_END + 0x002E=>'PLAYER_QUEST_LOG_8_2',
	UNIT_END + 0x002F=>'PLAYER_QUEST_LOG_8_3',
	UNIT_END + 0x0031=>'PLAYER_QUEST_LOG_8_5',
	UNIT_END + 0x0032=>'PLAYER_QUEST_LOG_9_1',
	UNIT_END + 0x0033=>'PLAYER_QUEST_LOG_9_2',
	UNIT_END + 0x0034=>'PLAYER_QUEST_LOG_9_3',
	UNIT_END + 0x0036=>'PLAYER_QUEST_LOG_9_5',
	UNIT_END + 0x0037=>'PLAYER_QUEST_LOG_10_1',
	UNIT_END + 0x0038=>'PLAYER_QUEST_LOG_10_2',
	UNIT_END + 0x0039=>'PLAYER_QUEST_LOG_10_3',
	UNIT_END + 0x003B=>'PLAYER_QUEST_LOG_10_5',
	UNIT_END + 0x003C=>'PLAYER_QUEST_LOG_11_1',
	UNIT_END + 0x003D=>'PLAYER_QUEST_LOG_11_2',
	UNIT_END + 0x003E=>'PLAYER_QUEST_LOG_11_3',
	UNIT_END + 0x0040=>'PLAYER_QUEST_LOG_11_5',
	UNIT_END + 0x0041=>'PLAYER_QUEST_LOG_12_1',
	UNIT_END + 0x0042=>'PLAYER_QUEST_LOG_12_2',
	UNIT_END + 0x0043=>'PLAYER_QUEST_LOG_12_3',
	UNIT_END + 0x0045=>'PLAYER_QUEST_LOG_12_5',
	UNIT_END + 0x0046=>'PLAYER_QUEST_LOG_13_1',
	UNIT_END + 0x0047=>'PLAYER_QUEST_LOG_13_2',
	UNIT_END + 0x0048=>'PLAYER_QUEST_LOG_13_3',
	UNIT_END + 0x004A=>'PLAYER_QUEST_LOG_13_5',
	UNIT_END + 0x004B=>'PLAYER_QUEST_LOG_14_1',
	UNIT_END + 0x004C=>'PLAYER_QUEST_LOG_14_2',
	UNIT_END + 0x004D=>'PLAYER_QUEST_LOG_14_3',
	UNIT_END + 0x004F=>'PLAYER_QUEST_LOG_14_5',
	UNIT_END + 0x0050=>'PLAYER_QUEST_LOG_15_1',
	UNIT_END + 0x0051=>'PLAYER_QUEST_LOG_15_2',
	UNIT_END + 0x0052=>'PLAYER_QUEST_LOG_15_3',
	UNIT_END + 0x0054=>'PLAYER_QUEST_LOG_15_5',
	UNIT_END + 0x0055=>'PLAYER_QUEST_LOG_16_1',
	UNIT_END + 0x0056=>'PLAYER_QUEST_LOG_16_2',
	UNIT_END + 0x0057=>'PLAYER_QUEST_LOG_16_3',
	UNIT_END + 0x0059=>'PLAYER_QUEST_LOG_16_5',
	UNIT_END + 0x005A=>'PLAYER_QUEST_LOG_17_1',
	UNIT_END + 0x005B=>'PLAYER_QUEST_LOG_17_2',
	UNIT_END + 0x005C=>'PLAYER_QUEST_LOG_17_3',
	UNIT_END + 0x005E=>'PLAYER_QUEST_LOG_17_5',
	UNIT_END + 0x005F=>'PLAYER_QUEST_LOG_18_1',
	UNIT_END + 0x0060=>'PLAYER_QUEST_LOG_18_2',
	UNIT_END + 0x0061=>'PLAYER_QUEST_LOG_18_3',
	UNIT_END + 0x0063=>'PLAYER_QUEST_LOG_18_5',
	UNIT_END + 0x0064=>'PLAYER_QUEST_LOG_19_1',
	UNIT_END + 0x0065=>'PLAYER_QUEST_LOG_19_2',
	UNIT_END + 0x0066=>'PLAYER_QUEST_LOG_19_3',
	UNIT_END + 0x0068=>'PLAYER_QUEST_LOG_19_5',
	UNIT_END + 0x0069=>'PLAYER_QUEST_LOG_20_1',
	UNIT_END + 0x006A=>'PLAYER_QUEST_LOG_20_2',
	UNIT_END + 0x006B=>'PLAYER_QUEST_LOG_20_3',
	UNIT_END + 0x006D=>'PLAYER_QUEST_LOG_20_5',
	UNIT_END + 0x006E=>'PLAYER_QUEST_LOG_21_1',
	UNIT_END + 0x006F=>'PLAYER_QUEST_LOG_21_2',
	UNIT_END + 0x0070=>'PLAYER_QUEST_LOG_21_3',
	UNIT_END + 0x0072=>'PLAYER_QUEST_LOG_21_5',
	UNIT_END + 0x0073=>'PLAYER_QUEST_LOG_22_1',
	UNIT_END + 0x0074=>'PLAYER_QUEST_LOG_22_2',
	UNIT_END + 0x0075=>'PLAYER_QUEST_LOG_22_3',
	UNIT_END + 0x0077=>'PLAYER_QUEST_LOG_22_5',
	UNIT_END + 0x0078=>'PLAYER_QUEST_LOG_23_1',
	UNIT_END + 0x0079=>'PLAYER_QUEST_LOG_23_2',
	UNIT_END + 0x007A=>'PLAYER_QUEST_LOG_23_3',
	UNIT_END + 0x007C=>'PLAYER_QUEST_LOG_23_5',
	UNIT_END + 0x007D=>'PLAYER_QUEST_LOG_24_1',
	UNIT_END + 0x007E=>'PLAYER_QUEST_LOG_24_2',
	UNIT_END + 0x007F=>'PLAYER_QUEST_LOG_24_3',
	UNIT_END + 0x0081=>'PLAYER_QUEST_LOG_24_5',
	UNIT_END + 0x0082=>'PLAYER_QUEST_LOG_25_1',
	UNIT_END + 0x0083=>'PLAYER_QUEST_LOG_25_2',
	UNIT_END + 0x0084=>'PLAYER_QUEST_LOG_25_3',
	UNIT_END + 0x0086=>'PLAYER_QUEST_LOG_25_5',
	UNIT_END + 0x0087=>'PLAYER_VISIBLE_ITEM_1_ENTRYID',
	UNIT_END + 0x0088=>'PLAYER_VISIBLE_ITEM_1_ENCHANTMENT',
	UNIT_END + 0x0089=>'PLAYER_VISIBLE_ITEM_2_ENTRYID',
	UNIT_END + 0x008A=>'PLAYER_VISIBLE_ITEM_2_ENCHANTMENT',
	UNIT_END + 0x008B=>'PLAYER_VISIBLE_ITEM_3_ENTRYID',
	UNIT_END + 0x008C=>'PLAYER_VISIBLE_ITEM_3_ENCHANTMENT',
	UNIT_END + 0x008D=>'PLAYER_VISIBLE_ITEM_4_ENTRYID',
	UNIT_END + 0x008E=>'PLAYER_VISIBLE_ITEM_4_ENCHANTMENT',
	UNIT_END + 0x008F=>'PLAYER_VISIBLE_ITEM_5_ENTRYID',
	UNIT_END + 0x0090=>'PLAYER_VISIBLE_ITEM_5_ENCHANTMENT',
	UNIT_END + 0x0091=>'PLAYER_VISIBLE_ITEM_6_ENTRYID',
	UNIT_END + 0x0092=>'PLAYER_VISIBLE_ITEM_6_ENCHANTMENT',
	UNIT_END + 0x0093=>'PLAYER_VISIBLE_ITEM_7_ENTRYID',
	UNIT_END + 0x0094=>'PLAYER_VISIBLE_ITEM_7_ENCHANTMENT',
	UNIT_END + 0x0095=>'PLAYER_VISIBLE_ITEM_8_ENTRYID',
	UNIT_END + 0x0096=>'PLAYER_VISIBLE_ITEM_8_ENCHANTMENT',
	UNIT_END + 0x0097=>'PLAYER_VISIBLE_ITEM_9_ENTRYID',
	UNIT_END + 0x0098=>'PLAYER_VISIBLE_ITEM_9_ENCHANTMENT',
	UNIT_END + 0x0099=>'PLAYER_VISIBLE_ITEM_10_ENTRYID',
	UNIT_END + 0x009A=>'PLAYER_VISIBLE_ITEM_10_ENCHANTMENT',
	UNIT_END + 0x009B=>'PLAYER_VISIBLE_ITEM_11_ENTRYID',
	UNIT_END + 0x009C=>'PLAYER_VISIBLE_ITEM_11_ENCHANTMENT',
	UNIT_END + 0x009D=>'PLAYER_VISIBLE_ITEM_12_ENTRYID',
	UNIT_END + 0x009E=>'PLAYER_VISIBLE_ITEM_12_ENCHANTMENT',
	UNIT_END + 0x009F=>'PLAYER_VISIBLE_ITEM_13_ENTRYID',
	UNIT_END + 0x00A0=>'PLAYER_VISIBLE_ITEM_13_ENCHANTMENT',
	UNIT_END + 0x00A1=>'PLAYER_VISIBLE_ITEM_14_ENTRYID',
	UNIT_END + 0x00A2=>'PLAYER_VISIBLE_ITEM_14_ENCHANTMENT',
	UNIT_END + 0x00A3=>'PLAYER_VISIBLE_ITEM_15_ENTRYID',
	UNIT_END + 0x00A4=>'PLAYER_VISIBLE_ITEM_15_ENCHANTMENT',
	UNIT_END + 0x00A5=>'PLAYER_VISIBLE_ITEM_16_ENTRYID',
	UNIT_END + 0x00A6=>'PLAYER_VISIBLE_ITEM_16_ENCHANTMENT',
	UNIT_END + 0x00A7=>'PLAYER_VISIBLE_ITEM_17_ENTRYID',
	UNIT_END + 0x00A8=>'PLAYER_VISIBLE_ITEM_17_ENCHANTMENT',
	UNIT_END + 0x00A9=>'PLAYER_VISIBLE_ITEM_18_ENTRYID',
	UNIT_END + 0x00AA=>'PLAYER_VISIBLE_ITEM_18_ENCHANTMENT',
	UNIT_END + 0x00AB=>'PLAYER_VISIBLE_ITEM_19_ENTRYID',
	UNIT_END + 0x00AC=>'PLAYER_VISIBLE_ITEM_19_ENCHANTMENT',
	UNIT_END + 0x00AD=>'PLAYER_CHOSEN_TITLE',
	UNIT_END + 0x00AE=>'PLAYER_FAKE_INEBRIATION',
	UNIT_END + 0x00AF=>'PLAYER_FIELD_PAD_0',
	UNIT_END + 0x00B0=>'PLAYER_FIELD_INV_SLOT_HEAD',
	UNIT_END + 0x00DE=>'PLAYER_FIELD_PACK_SLOT_1',
	UNIT_END + 0x00FE=>'PLAYER_FIELD_BANK_SLOT_1',
	UNIT_END + 0x0136=>'PLAYER_FIELD_BANKBAG_SLOT_1',
	UNIT_END + 0x0144=>'PLAYER_FIELD_VENDORBUYBACK_SLOT_1',
	UNIT_END + 0x015C=>'PLAYER_FIELD_KEYRING_SLOT_1',
	UNIT_END + 0x019C=>'PLAYER_FIELD_CURRENCYTOKEN_SLOT_1',
	UNIT_END + 0x01DC=>'PLAYER_FARSIGHT',
	UNIT_END + 0x01DE=>'PLAYER__FIELD_KNOWN_TITLES',
	UNIT_END + 0x01E0=>'PLAYER__FIELD_KNOWN_TITLES1',
	UNIT_END + 0x01E2=>'PLAYER__FIELD_KNOWN_TITLES2',
	UNIT_END + 0x01E4=>'PLAYER_FIELD_KNOWN_CURRENCIES',
	UNIT_END + 0x01E6=>'PLAYER_XP',
	UNIT_END + 0x01E7=>'PLAYER_NEXT_LEVEL_XP',
	UNIT_END + 0x01E8=>'PLAYER_SKILL_INFO_1_1',
	UNIT_END + 0x0368=>'PLAYER_CHARACTER_POINTS1',
	UNIT_END + 0x0369=>'PLAYER_CHARACTER_POINTS2',
	UNIT_END + 0x036A=>'PLAYER_TRACK_CREATURES',
	UNIT_END + 0x036B=>'PLAYER_TRACK_RESOURCES',
	UNIT_END + 0x036C=>'PLAYER_BLOCK_PERCENTAGE',
	UNIT_END + 0x036D=>'PLAYER_DODGE_PERCENTAGE',
	UNIT_END + 0x036E=>'PLAYER_PARRY_PERCENTAGE',
	UNIT_END + 0x036F=>'PLAYER_EXPERTISE',
	UNIT_END + 0x0370=>'PLAYER_OFFHAND_EXPERTISE',
	UNIT_END + 0x0371=>'PLAYER_CRIT_PERCENTAGE',
	UNIT_END + 0x0372=>'PLAYER_RANGED_CRIT_PERCENTAGE',
	UNIT_END + 0x0373=>'PLAYER_OFFHAND_CRIT_PERCENTAGE',
	UNIT_END + 0x0374=>'PLAYER_SPELL_CRIT_PERCENTAGE1',
	UNIT_END + 0x037B=>'PLAYER_SHIELD_BLOCK',
	UNIT_END + 0x037C=>'PLAYER_SHIELD_BLOCK_CRIT_PERCENTAGE',
	UNIT_END + 0x037D=>'PLAYER_EXPLORED_ZONES_1',
	UNIT_END + 0x03FD=>'PLAYER_REST_STATE_EXPERIENCE',
	UNIT_END + 0x03FE=>'PLAYER_FIELD_COINAGE',
	UNIT_END + 0x03FF=>'PLAYER_FIELD_MOD_DAMAGE_DONE_POS',
	UNIT_END + 0x0406=>'PLAYER_FIELD_MOD_DAMAGE_DONE_NEG',
	UNIT_END + 0x040D=>'PLAYER_FIELD_MOD_DAMAGE_DONE_PCT',
	UNIT_END + 0x0414=>'PLAYER_FIELD_MOD_HEALING_DONE_POS',
	UNIT_END + 0x0415=>'PLAYER_FIELD_MOD_HEALING_PCT',
	UNIT_END + 0x0416=>'PLAYER_FIELD_MOD_HEALING_DONE_PCT',
	UNIT_END + 0x0417=>'PLAYER_FIELD_MOD_TARGET_RESISTANCE',
	UNIT_END + 0x0418=>'PLAYER_FIELD_MOD_TARGET_PHYSICAL_RESISTANCE',
	UNIT_END + 0x0419=>'PLAYER_FIELD_BYTES',
	UNIT_END + 0x041A=>'PLAYER_AMMO_ID',
	UNIT_END + 0x041B=>'PLAYER_SELF_RES_SPELL',
	UNIT_END + 0x041C=>'PLAYER_FIELD_PVP_MEDALS',
	UNIT_END + 0x041D=>'PLAYER_FIELD_BUYBACK_PRICE_1',
	UNIT_END + 0x0429=>'PLAYER_FIELD_BUYBACK_TIMESTAMP_1',
	UNIT_END + 0x0435=>'PLAYER_FIELD_KILLS',
	UNIT_END + 0x0436=>'PLAYER_FIELD_TODAY_CONTRIBUTION',
	UNIT_END + 0x0437=>'PLAYER_FIELD_YESTERDAY_CONTRIBUTION',
	UNIT_END + 0x0438=>'PLAYER_FIELD_LIFETIME_HONORBALE_KILLS',
	UNIT_END + 0x0439=>'PLAYER_FIELD_BYTES2',
	UNIT_END + 0x043A=>'PLAYER_FIELD_WATCHED_FACTION_INDEX',
	UNIT_END + 0x043B=>'PLAYER_FIELD_COMBAT_RATING_1',
	UNIT_END + 0x0454=>'PLAYER_FIELD_ARENA_TEAM_INFO_1_1',
	UNIT_END + 0x0469=>'PLAYER_FIELD_HONOR_CURRENCY',
	UNIT_END + 0x046A=>'PLAYER_FIELD_ARENA_CURRENCY',
	UNIT_END + 0x046B=>'PLAYER_FIELD_MAX_LEVEL',
	UNIT_END + 0x046C=>'PLAYER_FIELD_DAILY_QUESTS_1',
	UNIT_END + 0x0485=>'PLAYER_RUNE_REGEN_1',
	UNIT_END + 0x0489=>'PLAYER_NO_REAGENT_COST_1',
	UNIT_END + 0x048C=>'PLAYER_FIELD_GLYPH_SLOTS_1',
	UNIT_END + 0x0492=>'PLAYER_FIELD_GLYPHS_1',
	UNIT_END + 0x0498=>'PLAYER_GLYPHS_ENABLED',
	UNIT_END + 0x0499=>'PLAYER_FIELD_PADDING',
	UNIT_END + 0x049A=>'PLAYER_END',
	
	PLAYER_SPELL_CRIT_PERCENTAGE+1=>'PLAYER_HOLY_SPELL_CRIT_PERCENTAGE',
	PLAYER_SPELL_CRIT_PERCENTAGE+2=>'PLAYER_FIRE_SPELL_CRIT_PERCENTAGE',
	PLAYER_SPELL_CRIT_PERCENTAGE+3=>'PLAYER_NATURE_SPELL_CRIT_PERCENTAGE',
	PLAYER_SPELL_CRIT_PERCENTAGE+4=>'PLAYER_FROST_SPELL_CRIT_PERCENTAGE',
	PLAYER_SPELL_CRIT_PERCENTAGE+5=>'PLAYER_SHADOW_SPELL_CRIT_PERCENTAGE',
	PLAYER_SPELL_CRIT_PERCENTAGE+6=>'PLAYER_ARCANE_SPELL_CRIT_PERCENTAGE',
	
	PLAYER_FIELD_ARENA_TEAM_INFO_1_1=>'PLAYER_FIELD_ARENA_TEAM_ID_2v2',
	PLAYER_FIELD_ARENA_TEAM_INFO_1_1+6=>'PLAYER_FIELD_ARENA_TEAM_ID_3v3',
	PLAYER_FIELD_ARENA_TEAM_INFO_1_1+12=>'PLAYER_FIELD_ARENA_TEAM_ID_5v5',
	
	PLAYER_FIELD_COMBAT_RATING=>'PLAYER_FIELD_ALL_WEAPON_SKILL_RATING',  // CR_WEAPON_SKILL
	PLAYER_FIELD_COMBAT_RATING+1=>'PLAYER_FIELD_DEFENCE_RATING',  // CR_DEFENSE_SKILL
	PLAYER_FIELD_COMBAT_RATING+2=>'PLAYER_FIELD_DODGE_RATING',  // CR_DODGE
	PLAYER_FIELD_COMBAT_RATING+3=>'PLAYER_FIELD_PARRY_RATING',  // CR_PARRY
	PLAYER_FIELD_COMBAT_RATING+4=>'PLAYER_FIELD_BLOCK_RATING',  // CR_BLOCK
	PLAYER_FIELD_COMBAT_RATING+5=>'PLAYER_FIELD_MELEE_HIT_RATING',  // CR_HIT_MELEE
	PLAYER_FIELD_COMBAT_RATING+6=>'PLAYER_FIELD_RANGED_HIT_RATING',  // CR_HIT_RANGED
	PLAYER_FIELD_COMBAT_RATING+7=>'PLAYER_FIELD_SPELL_HIT_RATING',  // CR_HIT_SPELL
	PLAYER_FIELD_COMBAT_RATING+8=>'PLAYER_FIELD_MELEE_CRIT_RATING',  // CR_CRIT_MELEE
	PLAYER_FIELD_COMBAT_RATING+9=>'PLAYER_FIELD_RANGED_CRIT_RATING',  // CR_CRIT_RANGED
	PLAYER_FIELD_COMBAT_RATING+10=>'PLAYER_FIELD_SPELL_CRIT_RATING',  // CR_CRIT_SPELL
	PLAYER_FIELD_COMBAT_RATING+11=>'PLAYER_FIELD_TAKEN_MELEE_HIT_RATING',  // CR_HIT_TAKEN_MELEE
	PLAYER_FIELD_COMBAT_RATING+12=>'PLAYER_FIELD_TAKEN_RANGED_HIT_RATING',  // CR_HIT_TAKEN_RANGED
	PLAYER_FIELD_COMBAT_RATING+13=>'PLAYER_FIELD_TAKEN_SPELL_HIT_RATING',  // CR_HIT_TAKEN_SPELL
	PLAYER_FIELD_COMBAT_RATING+14=>'PLAYER_FIELD_CRIT_TAKEN_MELEE_RATING',  // CR_CRIT_TAKEN_MELEE
	PLAYER_FIELD_COMBAT_RATING+15=>'PLAYER_FIELD_CRIT_TAKEN_RANGED_RATING',  // CR_CRIT_TAKEN_RANGED
	PLAYER_FIELD_COMBAT_RATING+16=>'PLAYER_FIELD_CRIT_TAKEN_SPELL_RATING',  // CR_CRIT_TAKEN_SPELL
	PLAYER_FIELD_COMBAT_RATING+17=>'PLAYER_FIELD_MELEE_HASTE_RATING',  // CR_HASTE_MELEE
	PLAYER_FIELD_COMBAT_RATING+18=>'PLAYER_FIELD_RANGED_HASTE_RATING',  // CR_HASTE_RANGED
	PLAYER_FIELD_COMBAT_RATING+19=>'PLAYER_FIELD_SPELL_HASTE_RATING',  // CR_HASTE_SPELL
	PLAYER_FIELD_COMBAT_RATING+20=>'PLAYER_FIELD_MELEE_WEAPON_SKILL_RATING',  // CR_WEAPON_SKILL_MAINHAND
	PLAYER_FIELD_COMBAT_RATING+21=>'PLAYER_FIELD_OFFHAND_WEAPON_SKILL_RATING',  // CR_WEAPON_SKILL_OFFHAND
	PLAYER_FIELD_COMBAT_RATING+22=>'PLAYER_FIELD_RANGED_WEAPON_SKILL_RATING',  // CR_WEAPON_SKILL_RANGED
	PLAYER_FIELD_COMBAT_RATING+23=>'PLAYER_FIELD_EXPERTISE_RATING',
	);
?>