/*
 * Talent calculator script
 * For work need additional data generated by talent_calc.php script
 */
var tc_maxpoints = tc_tabs!=1 ? tc_maxlevel - 9 : (tc_maxlevel - 20)>>2;
var tc_use_bonus = 0;
var tc_bild = new Array();
var tc_mode = new Array();
var tc_points = new Array(0, 0, 0);
var tc_totalpoints = 0;
var tc_base_bild_link = 0;

tc_cleanupBild();

function tc_cleanupBild()
{
	for (var i=0; i<tc_tabs; i++)
	{
		for (var row = 0; row < tc_row; row++)
			for (var col = 0; col < tc_col; col++)
				if (tc_tab[i+'_'+row+'_'+col])
				{
					tc_bild[i+'_'+row+'_'+col] = 0;
					tc_mode[i+'_'+row+'_'+col] = -1;
				}
		tc_points[i]=0;
	}
	tc_totalpoints = 0;
}
function tc_resetTree(i)
{
	for (var row = 0; row < tc_row; row++)
		for (var col = 0; col < tc_col; col++)
			if (tc_tab[i+'_'+row+'_'+col])
				tc_bild[i+'_'+row+'_'+col] = 0;
	tc_totalpoints-= tc_points[i];
	tc_points[i] = 0;
	tc_updateAllTabs();
	return false;
}
function tc_resetBild()
{
	for (var i=0; i<tc_tabs; i++)
		tc_resetTree(i);
	return false;
}
function tc_bildFromStr(str)
{
	for (var i=0,j=0; i<tc_tabs; i++)
		for (var row = 0; row < tc_row; row++)
			for (var col = 0; col < tc_col; col++)
				if (tc_tab[i+'_'+row+'_'+col])
				{
					var p = str ? parseInt(str.charAt(j)) : 0;
					tc_bild[i+'_'+row+'_'+col] = p;
					tc_points[i]+=p;
					tc_totalpoints+=p;
					j++;
				}
}
function tc_bildToStr()
{
	var str = '';
	for (var i=0; i<tc_tabs; i++)
		for (var row = 0; row < tc_row; row++)
			for (var col = 0; col < tc_col; col++)
				if (tc_tab[i+'_'+row+'_'+col])
					str+=tc_bild[i+'_'+row+'_'+col];
	return str;
}
function tc_addTalent(el)
{
	var l = el.id.split('_');
	var i = parseInt(l[1]);
	var row = parseInt(l[2]);
	var col = parseInt(l[3]);
	if (tc_canAddPoint(i, row, col))
	{
		tc_bild[i+'_'+row+'_'+col]++;
		tc_mode[i+'_'+row+'_'+col]=-1;
		tc_points[i]++;
		tc_totalpoints++;
		tc_updateAllTabs();
		tc_showTip(el,true);
	}
	return false;
}
function tc_removeTalent(el)
{
	var l = el.id.split('_');
	var i = parseInt(l[1]);
	var row = parseInt(l[2]);
	var col = parseInt(l[3]);
	if (tc_canRemovePoint(i, row, col))
	{
		tc_bild[i+'_'+row+'_'+col]--;
		tc_mode[i+'_'+row+'_'+col]=-1;
		tc_points[i]--;
		tc_totalpoints--;
		tc_updateAllTabs();
		tc_showTip(el,true);
	}
	return false;
}
function tc_showTip(el, update)
{
	if (el.tagName!='TD')
		return;
	var l = el.id.split('_');
	var i = parseInt(l[1]);
	var row = parseInt(l[2]);
	var col = parseInt(l[3]);
	var data = tc_tab[i+'_'+row+'_'+col];
	var rank = tc_bild[i+'_'+row+'_'+col];
	var id   = rank == 0 ? data.spells[0] : data.spells[rank-1];
	var req  = '';
	if (data.depend)
	{
		
	}
	if (row!=0)
	{
		req = '<tr><td' + (tc_points[i] < row*tc_point_per_row ? ' class=SpellErr' : '') +'>' + lang_req_points + '</td></tr>';
		req = req.replace(/<num>/, (row*tc_point_per_row));
		req = req.replace(/<name>/, tc_name[i]);
	}
	var text ='<table class=spell><tbody>'
	+ '<tr><td class=Name>' + tc_spell_desc[id].name + '</td></tr>'
	+ req
	+ '<tr><td>' + lang_rank +' '+ rank + ' / ' + data.max + '</td></tr>'
	+ '<tr><td class=Talent>'+tc_spell_desc[id].desc+'</td></tr>';
	if (rank!=0 && rank < data.max)
		text +='<tr><td><br>' + lang_next_rank + '</td></tr>'
			 + '<tr><td class=Talent>'+tc_spell_desc[data.spells[rank]].desc+'</td></tr>';
	text+='</tbody></table>';
	if (update)
		tt_UpdateTip(text);
	else
		Tip(text, TIMEDOWN, 0, OFFSETX, 60);
}
function tc_canAddPoint(i, row, col)
{
	var data = tc_tab[i+'_'+row+'_'+col];
	if (!data)
		return false;
	if (tc_totalpoints >=tc_maxpoints)
		return false;
	if (row*tc_point_per_row > tc_points[i])
		return false;
	if (data.max <= tc_bild[i+'_'+row+'_'+col])
		return false;
	var d = data.depend;
	if (d && tc_bild[d.id]<=d.rank)
		return false;
	return true;
}
function tc_canRemovePoint(i, row, col)
{
	var id	= i+'_'+row+'_'+col;
	var data  = tc_tab[id];
	var count = tc_bild[id];
	if (count == 0)
		return false;
	var amount = 0;
	for (var r = 0; r < tc_row, amount < tc_points[i]; r++)
	{
		var add = 0;
		for (var c = 0; c < tc_col; c++)
		{
			var t = tc_tab[i+'_'+r+'_'+c];
			if (t)
			{
				var a = tc_bild[i+'_'+r+'_'+c];
				add+=a;
				var d = t.depend;
				if (d && d.id==id && a && count-1<=d.rank)
					return false;
			}
		}
		if (r > row && add && amount<=r*tc_point_per_row)
			return false;
		amount+=add;
	}
	return true;
}

var tc_element=
[
 {frame:'icon-over-grey.gif',   dir:'../../images/bwicons/', color:'#1AFF1A', arrow:'green'},
 {frame:'icon-over-grey.gif',   dir:'../../images/bwicons/', color:'#FFFFFF', arrow:'grey'},
 {frame:'icon-over-yellow.gif', dir:'../../images/icons/',   color:'#FFD100', arrow:'yellow'},
 {frame:'icon-over-green.gif',  dir:'../../images/icons/',   color:'#1AFF1A', arrow:'green'}
];
function tc_getElementMode(i, row, col)
{
	var count = tc_bild[i+'_'+row+'_'+col];
	if (count == 0)
	{
		if (tc_canAddPoint(i, row, col)) return 0;
		return 1;
	}
	else if (count == tc_tab[i+'_'+row+'_'+col].max) return 2;
	return 3;
}
function tc_updateAllTabs()
{
	for (var i=0; i<tc_tabs; i++)
		tc_updateTab(i);
	tc_updateBildLink();
}
function tc_updateBildLink()
{
	var bildhref = document.getElementById('talent_bild_link');
	if (bildhref)
	{
		if (tc_base_bild_link == 0)
			tc_base_bild_link = bildhref.href;
		bildhref.href = tc_base_bild_link + (tc_totalpoints ? '&bild=' + tc_bildToStr() : '');
	}
}
function tc_updateTab(i)
{
	document.getElementById('talent_point_'+i).innerHTML = tc_points[i];
	var max = tc_points[i] == 0 ? tc_row : tc_points[i]/tc_point_per_row+2;
	for (var r = 0; r < tc_row, r < max; r++)
		for (var c = 0; c < tc_col; c++)
		{
			var id = i+'_'+r+'_'+c;
			if (!tc_tab[id])
				continue;
			tc_updateElment(id, tc_getElementMode(i, r, c));
		}
}
function tc_updateElment(id, mode)
{
	if (mode==tc_mode[id])
		return;
	tc_mode[id] = mode;
	var d = tc_tab[id];
	var div = document.getElementById('talent_'+id).firstChild;
	var m = tc_element[mode];
	for(var img = div.firstChild; img!=null; img = img.nextSibling)
	{
		if (img.id=='ico') img.src = m.dir+d.icon;
		else if (img.id=='brd') img.src = '../../images/talentcalc/'+m.frame;
		else if (img.id=='rnk'){img.style.color = m.color;img.innerHTML = tc_bild[id] + '/' + d.max;}
		else if (img.id=='arw') img.src = '../../images/talentcalc/'+d.depend.img+'-'+m.arrow+'.gif';
	}
}
function tc_renderTree(element)
{
  var text = ''
  + '<table class=talenttab><tbody>'
  + '<tr><td colspan=' + tc_tabs + ' class=head>' + lang_header + '</td></tr>'
  + '<tr>';
  for (var i=0; i<tc_tabs; i++)
  {
	text+= '<td style="position: relative;">';
	text+= '<img src="../../images/talentcalc/t_'+tc_showclass+'_'+i+'.jpg" style="position: absolute; width: '+(58*tc_col+10)+'px; height:'+(58*tc_row+10)+'px;"></div>';
	text+= '<table class=talent cellSpacing=0><tbody>';
	for (var row = 0; row < tc_row; row++)
	{
	  text+= '<tr valign=top>';
	  for (var col = 0; col < tc_col; col++)
	  {
		var id = i+'_'+row+'_'+col;
		var d =  tc_tab[id];
		text+= '<td id="talent_'+id+'" onclick="return tc_addTalent(this);" oncontextmenu="return tc_removeTalent(this);" onmouseover="tc_showTip(this, false);">';
		if (d)
		{
			var mode = tc_getElementMode(i, row, col);
			tc_mode[id] = mode;
			var m = tc_element[mode];
			text+= '<div style="position: relative;">'
			text+= '<img id="ico" src="'+m.dir+d.icon+'" width=44 height=44 style="position: absolute; left: 2px; top: 2px;">';
			text+= '<img id="brd" src="../../images/talentcalc/'+m.frame+'" style="position: absolute; left: 0px; top: 0px;">';
			text+= '<div id="rnk" style="position: absolute; left: 34px; top: 38px; color:'+m.color+';">'+ tc_bild[id] + '/' + d.max + '</div>';
			if (d.depend)
				text+= '<img id="arw" src="../../images/talentcalc/'+d.depend.img+'-'+m.arrow+'.gif" style="position: absolute; border: 0px; left: '+d.depend.x+'px; top: '+d.depend.y+'px;">';
			text+= '</div>';
		}
		text+= '</td>';
	  }
	  text+= '</tr>';
	}
	text+= '</tbody></table></td>';
  }
  text+= '<tr class=bottom>';
  for (i = 0;i<tc_tabs;i++)
  {
	text+= '<td><div style="position: relative;">'
		+ '<img align="left" src="../../images/talentcalc/'+tc_showclass+'_'+i+'.png">'
		+ tc_name[i] + ': '
		+ '<span id="talent_point_'+i+'">'+tc_points[i]+'</span>'
		+ '<a href=# onclick="return tc_resetTree('+i+');" style="position: absolute; top: 2px; right: 2px;"><img src="../../images/talentcalc/reset.gif" border=0></a>'
		+ '</div></td>';
  }
  text+= '</tr>';
  text+= '</tbody></table>';
  document.getElementById(element).innerHTML = text;
  tc_updateBildLink();
}